"""empty message

Revision ID: e64b9bb3f7d4
Revises: c99e66d51347
Create Date: 2024-04-13 13:02:28.992051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64b9bb3f7d4'
down_revision = 'c99e66d51347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('savings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wants', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('needs', sa.Float(), nullable=True))
        batch_op.drop_column('amount')
        batch_op.drop_column('description')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=250), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), nullable=False))
        batch_op.drop_column('needs')
        batch_op.drop_column('wants')
        batch_op.drop_column('savings')

    # ### end Alembic commands ###
